apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ola-mundo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-ola-mundo
  template:
    metadata:
      labels:
        app: nginx-ola-mundo
    spec:
      imagePullSecrets:
      - name: acr-secret  # <-- Aqui estamos vinculando a autenticação
      containers:
      - name: nginx-ola-mundo
        image: devsquads.azurecr.io/nginx-ola-mundo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ola-mundo
spec:
  selector:
    app: nginx-ola-mundo
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

