name: Build and Push to Azure ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: devsquads.azurecr.io
          username: devsquads
          password: ${{ secrets.ACR_PASSWORD }}  # Usando secret seguro

      - name: Build Docker Image
        run: |
          NEW_TAG=$(date +%Y%m%d%H%M%S)  # Gera um novo número de versão baseado no timestamp
          docker build -t devsquads.azurecr.io/nginx-ola-mundo:$NEW_TAG .
          docker tag devsquads.azurecr.io/nginx-ola-mundo:$NEW_TAG devsquads.azurecr.io/nginx-ola-mundo:latest
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Push Docker Image to ACR
        run: |
          docker push devsquads.azurecr.io/nginx-ola-mundo:$NEW_TAG
          docker push devsquads.azurecr.io/nginx-ola-mundo:latest

      - name: Atualizar tag da imagem no values.yaml
        run: |
          sed -i "s|tag:.*|tag: \"$NEW_TAG\"|" helm/values.yaml
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add helm/values.yaml
          git commit -m "Atualizando tag da imagem para $NEW_TAG"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
